name: Build and Publish (Quarto)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr","rmarkdown","htmltools"))'

      - name: Render how_to_upload_and_download_from_zenodo.qmd to HTML
        run: |
          quarto render how_to_upload_and_download_from_zenodo.qmd --to html --output index.html
          # quarto render how_to_upload_and_download_from_zenodo.qmd --to gfm  --output README.md

      # - name: Commit updated README.md to default branch
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore: update README.md from index.qmd [skip ci]"
      #     file_pattern: README.md

      - name: Prepare publish dir
        run: |
          rm -rf public
          mkdir -p public
          cp index.html public/

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          # Set to false to create .nojekyll and bypass Jekyll processing
          enable_jekyll: false
